/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SalesCasesIndexRouteImport } from './routes/sales-cases.index'
import { Route as LotsIndexRouteImport } from './routes/lots.index'
import { Route as SalesCasesNewRouteImport } from './routes/sales-cases.new'
import { Route as SalesCasesIdRouteImport } from './routes/sales-cases.$id'
import { Route as ReservationCasesIdRouteImport } from './routes/reservation-cases.$id'
import { Route as LotsNewRouteImport } from './routes/lots.new'
import { Route as LotsIdRouteImport } from './routes/lots.$id'
import { Route as ExternalPriceCheckRouteImport } from './routes/external.price-check'
import { Route as ConsignmentCasesIdRouteImport } from './routes/consignment-cases.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesCasesIndexRoute = SalesCasesIndexRouteImport.update({
  id: '/sales-cases/',
  path: '/sales-cases/',
  getParentRoute: () => rootRouteImport,
} as any)
const LotsIndexRoute = LotsIndexRouteImport.update({
  id: '/lots/',
  path: '/lots/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesCasesNewRoute = SalesCasesNewRouteImport.update({
  id: '/sales-cases/new',
  path: '/sales-cases/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesCasesIdRoute = SalesCasesIdRouteImport.update({
  id: '/sales-cases/$id',
  path: '/sales-cases/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationCasesIdRoute = ReservationCasesIdRouteImport.update({
  id: '/reservation-cases/$id',
  path: '/reservation-cases/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LotsNewRoute = LotsNewRouteImport.update({
  id: '/lots/new',
  path: '/lots/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LotsIdRoute = LotsIdRouteImport.update({
  id: '/lots/$id',
  path: '/lots/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ExternalPriceCheckRoute = ExternalPriceCheckRouteImport.update({
  id: '/external/price-check',
  path: '/external/price-check',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsignmentCasesIdRoute = ConsignmentCasesIdRouteImport.update({
  id: '/consignment-cases/$id',
  path: '/consignment-cases/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/consignment-cases/$id': typeof ConsignmentCasesIdRoute
  '/external/price-check': typeof ExternalPriceCheckRoute
  '/lots/$id': typeof LotsIdRoute
  '/lots/new': typeof LotsNewRoute
  '/reservation-cases/$id': typeof ReservationCasesIdRoute
  '/sales-cases/$id': typeof SalesCasesIdRoute
  '/sales-cases/new': typeof SalesCasesNewRoute
  '/lots/': typeof LotsIndexRoute
  '/sales-cases/': typeof SalesCasesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/consignment-cases/$id': typeof ConsignmentCasesIdRoute
  '/external/price-check': typeof ExternalPriceCheckRoute
  '/lots/$id': typeof LotsIdRoute
  '/lots/new': typeof LotsNewRoute
  '/reservation-cases/$id': typeof ReservationCasesIdRoute
  '/sales-cases/$id': typeof SalesCasesIdRoute
  '/sales-cases/new': typeof SalesCasesNewRoute
  '/lots': typeof LotsIndexRoute
  '/sales-cases': typeof SalesCasesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/consignment-cases/$id': typeof ConsignmentCasesIdRoute
  '/external/price-check': typeof ExternalPriceCheckRoute
  '/lots/$id': typeof LotsIdRoute
  '/lots/new': typeof LotsNewRoute
  '/reservation-cases/$id': typeof ReservationCasesIdRoute
  '/sales-cases/$id': typeof SalesCasesIdRoute
  '/sales-cases/new': typeof SalesCasesNewRoute
  '/lots/': typeof LotsIndexRoute
  '/sales-cases/': typeof SalesCasesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/consignment-cases/$id'
    | '/external/price-check'
    | '/lots/$id'
    | '/lots/new'
    | '/reservation-cases/$id'
    | '/sales-cases/$id'
    | '/sales-cases/new'
    | '/lots/'
    | '/sales-cases/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/consignment-cases/$id'
    | '/external/price-check'
    | '/lots/$id'
    | '/lots/new'
    | '/reservation-cases/$id'
    | '/sales-cases/$id'
    | '/sales-cases/new'
    | '/lots'
    | '/sales-cases'
  id:
    | '__root__'
    | '/'
    | '/consignment-cases/$id'
    | '/external/price-check'
    | '/lots/$id'
    | '/lots/new'
    | '/reservation-cases/$id'
    | '/sales-cases/$id'
    | '/sales-cases/new'
    | '/lots/'
    | '/sales-cases/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsignmentCasesIdRoute: typeof ConsignmentCasesIdRoute
  ExternalPriceCheckRoute: typeof ExternalPriceCheckRoute
  LotsIdRoute: typeof LotsIdRoute
  LotsNewRoute: typeof LotsNewRoute
  ReservationCasesIdRoute: typeof ReservationCasesIdRoute
  SalesCasesIdRoute: typeof SalesCasesIdRoute
  SalesCasesNewRoute: typeof SalesCasesNewRoute
  LotsIndexRoute: typeof LotsIndexRoute
  SalesCasesIndexRoute: typeof SalesCasesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-cases/': {
      id: '/sales-cases/'
      path: '/sales-cases'
      fullPath: '/sales-cases/'
      preLoaderRoute: typeof SalesCasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lots/': {
      id: '/lots/'
      path: '/lots'
      fullPath: '/lots/'
      preLoaderRoute: typeof LotsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-cases/new': {
      id: '/sales-cases/new'
      path: '/sales-cases/new'
      fullPath: '/sales-cases/new'
      preLoaderRoute: typeof SalesCasesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-cases/$id': {
      id: '/sales-cases/$id'
      path: '/sales-cases/$id'
      fullPath: '/sales-cases/$id'
      preLoaderRoute: typeof SalesCasesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservation-cases/$id': {
      id: '/reservation-cases/$id'
      path: '/reservation-cases/$id'
      fullPath: '/reservation-cases/$id'
      preLoaderRoute: typeof ReservationCasesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lots/new': {
      id: '/lots/new'
      path: '/lots/new'
      fullPath: '/lots/new'
      preLoaderRoute: typeof LotsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lots/$id': {
      id: '/lots/$id'
      path: '/lots/$id'
      fullPath: '/lots/$id'
      preLoaderRoute: typeof LotsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/external/price-check': {
      id: '/external/price-check'
      path: '/external/price-check'
      fullPath: '/external/price-check'
      preLoaderRoute: typeof ExternalPriceCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consignment-cases/$id': {
      id: '/consignment-cases/$id'
      path: '/consignment-cases/$id'
      fullPath: '/consignment-cases/$id'
      preLoaderRoute: typeof ConsignmentCasesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsignmentCasesIdRoute: ConsignmentCasesIdRoute,
  ExternalPriceCheckRoute: ExternalPriceCheckRoute,
  LotsIdRoute: LotsIdRoute,
  LotsNewRoute: LotsNewRoute,
  ReservationCasesIdRoute: ReservationCasesIdRoute,
  SalesCasesIdRoute: SalesCasesIdRoute,
  SalesCasesNewRoute: SalesCasesNewRoute,
  LotsIndexRoute: LotsIndexRoute,
  SalesCasesIndexRoute: SalesCasesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
